#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CollectingMobile.Resource", IsApplication=true)]

namespace CollectingMobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::CollectingMobile.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::CollectingMobile.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::CollectingMobile.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int button = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int listSelector = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int textColor = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int textInAccent = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int toolbarTextColor = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circleButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int gradient = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_add_a_photo_black_36dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_add_a_photo_white_18dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_add_a_photo_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_add_a_photo_white_36dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_border_outer_black_36dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_border_outer_white_18dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_border_outer_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_border_outer_white_36dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_check_circle_white_24dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_done_all_black_36dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_done_all_white_36dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_done_black_36dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_done_white_24dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_done_white_36dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_location_searching_black_36dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_location_searching_white_18dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_location_searching_white_24dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_location_searching_white_36dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_lock_outline_black_36dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_lock_outline_white_18dp = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_lock_outline_white_24dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_lock_outline_white_36dp = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_perm_identity_black_36dp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_perm_identity_white_18dp = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_perm_identity_white_24dp = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_perm_identity_white_36dp = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_signal_wifi_off_black_36dp = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_signal_wifi_off_white_18dp = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_signal_wifi_off_white_24dp = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_signal_wifi_off_white_36dp = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int inRebus = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int Location = 2131230738;
			
			// aapt resource value: 0x7f080019
			public const int LocationButton = 2131230745;
			
			// aapt resource value: 0x7f080013
			public const int LocationText = 2131230739;
			
			// aapt resource value: 0x7f080023
			public const int Logout = 2131230755;
			
			// aapt resource value: 0x7f080003
			public const int MyButton = 2131230723;
			
			// aapt resource value: 0x7f080021
			public const int NoConnectionButton = 2131230753;
			
			// aapt resource value: 0x7f080005
			public const int PhotoLayout = 2131230725;
			
			// aapt resource value: 0x7f080017
			public const int PhotoView = 2131230743;
			
			// aapt resource value: 0x7f080026
			public const int PopupRequest = 2131230758;
			
			// aapt resource value: 0x7f080015
			public const int QR = 2131230741;
			
			// aapt resource value: 0x7f08001a
			public const int QRButton = 2131230746;
			
			// aapt resource value: 0x7f080016
			public const int QRText = 2131230742;
			
			// aapt resource value: 0x7f080025
			public const int RefreshRequests = 2131230757;
			
			// aapt resource value: 0x7f08000b
			public const int RequestsListView = 2131230731;
			
			// aapt resource value: 0x7f080000
			public const int RootLoginActivity = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int RootRequestsActivity = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int RootSpecimenInputActivity = 2131230732;
			
			// aapt resource value: 0x7f08001d
			public const int RootSpecimensActivity = 2131230749;
			
			// aapt resource value: 0x7f08000f
			public const int SamplingPosition = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int SamplingPositionText = 2131230736;
			
			// aapt resource value: 0x7f08001c
			public const int SaveButton = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int SpecimenslistView = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int TakePhoto = 2131230747;
			
			// aapt resource value: 0x7f080024
			public const int Test = 2131230756;
			
			// aapt resource value: 0x7f08001f
			public const int Toolbar = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int ToolbarText = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int contentFrame = 2131230754;
			
			// aapt resource value: 0x7f080002
			public const int password = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int photoRetakeImageView = 2131230726;
			
			// aapt resource value: 0x7f08000e
			public const int relativeLayout1 = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int relativeLayout2 = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int relativeLayout3 = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int relativeLayout4 = 2131230744;
			
			// aapt resource value: 0x7f080009
			public const int requestDate = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int requestDescription = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int requestId = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int textView1 = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int toolbar = 2131230733;
			
			// aapt resource value: 0x7f080001
			public const int username = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PhotoLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RequestListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Requests = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SpecimenInput = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SpecimenItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Specimens = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int menuRequests = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int popupRequest = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060016
			public const int ApplicationName = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int Authenticating = 2131099672;
			
			// aapt resource value: 0x7f06000a
			public const int CheckNetwork = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int Connected = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int Geolocation = 2131099665;
			
			// aapt resource value: 0x7f060017
			public const int LoadingRequests = 2131099671;
			
			// aapt resource value: 0x7f060007
			public const int Login = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Logout = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int NoLocationService = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int OK = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int OfflineMode = 2131099661;
			
			// aapt resource value: 0x7f06001a
			public const int OpenCamera = 2131099674;
			
			// aapt resource value: 0x7f060001
			public const int Password = 2131099649;
			
			// aapt resource value: 0x7f06001b
			public const int PleaseRelog = 2131099675;
			
			// aapt resource value: 0x7f06000f
			public const int QR = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int Requests = 2131099650;
			
			// aapt resource value: 0x7f060012
			public const int SamplingPosition = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int Saved = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int SearchingLocation = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int ServerProblem = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int SpecimenInput = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int Specimens = 2131099651;
			
			// aapt resource value: 0x7f060019
			public const int Test = 2131099673;
			
			// aapt resource value: 0x7f060015
			public const int UploadError = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int UploadSuccess = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int Uploading = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int Username = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int WebException = 2131099654;
			
			// aapt resource value: 0x7f06001c
			public const int copyright = 2131099676;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
